// <auto-generated />
namespace Tekegy_SendSms_Task.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addMessageTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addMessageTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201804252113285_addMessageTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
